// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Permission struct {
	PermissionID int32
	Code         sql.NullString
	Description  sql.NullString
}

type Role struct {
	RoleID      int32
	Name        sql.NullString
	Description sql.NullString
}

type RolesPermission struct {
	PermissionID sql.NullInt32
	RoleID       sql.NullInt32
}

type User struct {
	UserID       uuid.UUID
	Email        string
	Name         sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
